name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch (or change to your default branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the desired Node.js version

    - name: Install dependencies
      run: |
        npm install
        # Install node-fetch@2 and undici to polyfill ReadableStream
        npm install node-fetch@2 undici

    - name: Build the project
      run: |
        # Add polyfill to Node.js environment
        echo "require('node-fetch'); require('undici');" > setup.js
        node setup.js
        # Run expo export to build the static web files into the dist folder
        npx expo export --platform web

    - name: Deploy to GitHub Pages
      run: |
        npm run deploy  # This will run the `gh-pages` deploy script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided by GitHub Actions
